export const apiFormatWithTime = 'YYYY-MM-DDTHH:mm:ss'
export const apiFormat = 'YYYY-MM-DD'
export const displayFormat = 'YYYY-MM-DD'
export const monthFormat = 'YYYY-MM'
export const displayFormatWithMinute = 'YYYY-MM-DD HH:mm'
export const displayFormatWithTime = 'YYYY-MM-DD HH:mm:ss'
export const dateFormat = 'YYYY-MM-DD HH:mm:ss'
